### ISSUE TITLE
The "Run locally" instructions should pay lip service to installing webpack

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script-demo#1]
To make things easier for someone who hasn't used webpack but wants to try caffeine-script, add something like

(optional) 
npm install -g webpack

**Comment by shanebdavis** [comment]
Hmm. Webpack should be a dependency... But its binary may not get put in the path with just "npm install". If you do 

```
npm install -g coffee-script
```

Everything should get installed properly; I think.

**Comment by shanebdavis** [comment]
I fixed the README - it forgot to mention "npm install" at all :)
